### ISSUE TITLE
JOSS comments (Gabe)

### ISSUE THREAD

**Issue by gabeerion** [DOE-NCI-MOSSAIC/FrESCO#1]
Hi! I'm one of the reviewers on the paper submission to JOSS. I enjoyed reading the paper and agree this is a very useful area to develop software for! Thank you for contributing this exciting software. My review itself is in the joss-reviews issue and is mostly a list of checkboxes; I think the paper is well-written, the references are great, and the open-source nature of the software is well-established. I am posting here to discuss some specific areas in more depth than a check-box so we can address them and I can check them off my review! I will try to indicate with "ideally" comments/requests that are not mandatory but that from my perspective would greatly improve the value of the paper. Some of these comments may stem from a misunderstanding of the package or from something I missed in my own attempts to use it, and if so please correct me! Finally, I'm glad to break this out into separate specific issues in the repo if that's helpful.

# Scholarly effort
* The package does great along many of these axes. However, my understanding the main value proposition is to make it easy for non-NLP experts to abstract structured data from pathology reports. To that end, I think there's not enough documentation for a newcomer and at least some increase in documentation is necessary (see below).

# Installation
I was able to install the software by following the directions; however I don't currently see a reason the dependencies can't be handled automatically and/or that installation should require cloning the repo. In general a Python package submitted to JOSS should be pip-installable. If this isn't possible it would be good to know the reason for it. I also think if the package targets users with little programming knowledge it would be ideal for the pip install to provide an acutal command line utility (so that, for example, I could run something like `fresco --config cfg.yml --datadir path_to_dir --model_output path_to_output` from any directory, not just the repo).

# Functionality
I have encountered small issues so far that have prevented me from fully exploring the functionality of the code. They should be easily fixable. For example, on initially cloning the repo and running the scripts in `tests` I get an import error for the 'validate' module. I also get a KeyError on 'groups' on 'Step 2: Train a clc model' of the Readme.

# Documentation
Some of this is covered above, but I think there needs to be more documentation, which I will try to divide into essential areas and nice-to-haves
* Installation -- good, but would be nice to have automated dependency management (and see discussion of pip above).
* Example usage -- currently minimal. I think it is essential to have an example starting from a well-known dataset in a widely used format. For example, running through the IMDB example starting from a standard format of the IMDB dataset (ie from the Stanford website). Ideally, there would also be examples (possibly in notebook form) of each example dataset and model type, with a little more information on the datasets and model types included in the package. As someone new to this specific application area, I might want to know more about what the data usually look like, and as someone new to NLP, I might want to know more about which model to choose.
* Functionality documentation -- I think the package is intended to be usable by NLP practitioners as well, and they might want to make use of the Python functions. These appear to be well documented but ideally there would be a readthedocs type interface for them.
* Tests -- There are manual tests that I will evaluate more once they are running on my machine. Automated tests would be the ideal.

# Paper
Overall I think the paper is well-written. I have one comment, which is that ideally the statement of need would address why the models included in this software can't be run using their original implementations. My guess is this software aims to make them easier to use, and it would be great to provide a couple examples somewhere in the paper explaining why.

Thanks again for submitting this paper, and I would be very happy to chat more about any of these areas!

**Comment by aspannaus** [comment]
Hi @gabeerion,

Thanks for the comments and suggestions. We're presently working on getting the repo pip-installable, putting the documentation on readthedocs, and adding some notebook examples. 

We can add some text to the manuscript describing why we cannot use the actual production code. The main development is in an air-gapped system with private health data, and we have restrictions on what can and cannot be moved outside. We believe that this repository is a reasonable compromise; if the required data files are supplied, the code runs similarly in both environments. 

Regarding the issue you're seeing with training a clc model, I think the data path in the model_args file needs to point to the clc directory. The sample data files provided there has that missing key you mention above. 

We've corrected the issue with the scripts in the tests folder as well. 

We will finish internal testing with the reorganization to make the repo pip-installable and push the changes early next week.

Thanks again for the helpful comments and suggestions.

**Comment by aspannaus** [comment]
Hey @gabeerion and @[SimonBiggs](https://github.com/SimonBiggs), 

We've made our edits based on @gabeerion's helpful comments and suggestions. Please continue with the review and let us know what you all think. Thanks!

**Comment by gabeerion** [comment]
Hi all, thank you for your hard work on the repo! I have updated my review in the joss-reviews thread and only have one or two comments left. I think the last two points I have are regarding functionality documentation and example usage:
1 - The notebooks are very helpful, I think the last example usage that would be good is showing how to go start with a trained model and create/save predictions on a new unlabeled dataset.
2 - For documentation, brief explanations of all the config.yml parameters seems important to me, ideally in the readthedocs somewhere.

If these can be completed I think I'll be able to finalize the review in short order. Thank you!

**Comment by aspannaus** [comment]
Hey @gabeerion,

Thanks for the comments and feedback. We've updated the repository with an additional example notebook and description of the args in the config.yml file. Let us know if you see anything else.

Thanks!

**Comment by gabeerion** [comment]
Hi, thanks for these edits! I think they're great. I'm going to recommend two changes but I don't think either of them are essential to finish my review so I will mark it complete.

1 - It would be good for the example notebook to mention that it is essentially  a breakdown of how `use_model.py` works -- it took me til halfway through or so to realize

2 - The explanations of the args are very helpful! For some reason they're formatted nicely on Github but the formatting breaks on readthedocs. It'd be nice to fix -- but again, not worth delaying my review completion over.

Thanks for sharing the great work!

**Comment by aspannaus** [comment]
Hi @gabeerion,

Thanks for the helpful comments and feedback on the repo. We went ahead and made a few edits based on your comments above; it makes everything flow a bit more smoothly.

Thanks again!
