### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by SimonBiggs** [DOE-NCI-MOSSAIC/FrESCO#26]
Hi,

I went to the documentation page and did not see any description within the docs on how to install, or what I can do with this package:

https://doe-nci-fresco.readthedocs.io/

Cheers,
Simon

**Comment by zachfox** [comment]
Hi @SimonBiggs, 

Thanks very much for the comment. I have updated https://doe-nci-fresco.readthedocs.io/ to provide instructions for installation and usage. 

Zach
